services:
    laravel:
        env_file:
          - .env
        build:
            context: .
        depends_on:
          postgres:
            condition: service_healthy
        restart: unless-stopped
        ports:
          - "127.0.0.1:8000:8000"
        command: sh -c "php artisan migrate && php artisan serve"
      
    postgres:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]