networks:
  traefik: { external: true }
  notte: { external: false }

volumes:
  postgres-data:

services:
  bot:
    environment:
      - APP_URL=https://notte.daniil.online
      - LOG_CHANNEL=errorlog
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=notte
      - DB_USERNAME=root
      - DB_PASSWORD
      - TELEGRAM_BOT_TOKEN
    image: trckster/notte
    networks: [ traefik, notte ]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.notte-http.rule=Host(`notte.daniil.online`)
      - traefik.http.routers.notte-http.entrypoints=http
      - traefik.http.routers.notte-http.middlewares=https-redirect
      - traefik.http.routers.notte-https.rule=Host(`notte.daniil.online`)
      - traefik.http.routers.notte-https.entrypoints=https
      - traefik.http.routers.notte-https.tls=true
      - traefik.http.routers.notte-https.tls.certresolver=le
      - traefik.http.services.notte.loadbalancer.server.port=80

  postgres:
    image: postgres:17
    networks: [ notte ]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notte
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
