version: "3.9"

networks:
  traefik-public: { external: true }
  notte: { external: false }

volumes:
  postgres-data:

services:
  laravel:
    environment:
      - APP_URL=https://notte.daniil.online
      - LOG_CHANNEL=errorlog
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=notte
      - DB_USERNAME=root
      - DB_PASSWORD
      - TELEGRAM_BOT_TOKEN
    image: trckster/notte
    networks: [ traefik-public, notte ]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${PROJECT_NAME?}-http.rule=Host(`notte.daniil.online`)
        - traefik.http.routers.${PROJECT_NAME?}-http.entrypoints=http
        - traefik.http.routers.${PROJECT_NAME?}-http.middlewares=https-redirect
        - traefik.http.routers.${PROJECT_NAME?}-https.rule=Host(`notte.daniil.online`)
        - traefik.http.routers.${PROJECT_NAME?}-https.entrypoints=https
        - traefik.http.routers.${PROJECT_NAME?}-https.tls=true
        - traefik.http.routers.${PROJECT_NAME?}-https.tls.certresolver=le
        - traefik.http.services.${PROJECT_NAME?}.loadbalancer.server.port=80

  postgres:
    image: postgres:16.3
    networks: [ notte ]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notte
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
